
services:
#  restaurant-mng:
#    build:
#      context: ./
#    container_name: restaurant-mng
#    ports:
#      - "1241:1241"
#    environment:
#      - SPRING_PROFILES_ACTIVE=local
##    networks:
##      - postgres

  rabbimq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
#    networks:
#      - postgres